apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: fb9e28b0059521331345cb4b2134943bc464fa41
    app.openshift.io/vcs-uri: https://github.com/remiserra/nextjsapp
  labels:
    app: nextjsapp-rs
    app.kubernetes.io/instance: nextjsapp-rs
    app.kubernetes.io/name: nextjsapp-rs
  name: nextjs-sample-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: nextjsapp-rs
    app.kubernetes.io/instance: nextjsapp-rs
    app.kubernetes.io/name: nextjsapp-rs
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: fb9e28b0059521331345cb4b2134943bc464fa41
    app.openshift.io/vcs-uri: https://github.com/remiserra/nextjsapp
  labels:
    app: nextjsapp-rs
    app.kubernetes.io/instance: nextjsapp-rs
    app.kubernetes.io/name: nextjsapp-rs
  name: nextjs-sample-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nextjsapp-rs
      app.kubernetes.io/instance: nextjsapp-rs
      app.kubernetes.io/name: nextjsapp-rs
  template:
    metadata:
      annotations:
        app.openshift.io/runtime: js
        app.openshift.io/vcs-ref: fb9e28b0059521331345cb4b2134943bc464fa41
        app.openshift.io/vcs-uri: https://github.com/remiserra/nextjsapp
      labels:
        app: nextjsapp-rs
        app.kubernetes.io/instance: nextjsapp-rs
        app.kubernetes.io/name: nextjsapp-rs
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/remiserra/nextjsapp-rs:fb9e28b0059521331345cb4b2134943bc464fa41
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nextjs-sample-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: fb9e28b0059521331345cb4b2134943bc464fa41
    app.openshift.io/vcs-uri: https://github.com/remiserra/nextjsapp
  labels:
    app: nextjsapp-rs
    app.kubernetes.io/instance: nextjsapp-rs
    app.kubernetes.io/name: nextjsapp-rs
  name: nextjs-sample-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: nextjs-sample-app
    weight: 100
  wildcardPolicy: None
